[workspace]
resolver = "2"

members = [
    "docs",
    "axum_serde_valid",
    "serde_valid",
    "serde_valid_derive",
    "serde_valid_literal",
]

[workspace.package]
edition = "2021"
version = "0.16.3"
license = "MIT"
repository = "https://github.com/yassun4dev/serde_valid.git"
authors = ["yassun4dev <yassun4dev@outlook.com>"]
keywords = ["validation", "serde", "json_schema"]

[workspace.dependencies]
regex = "^1.6"
paste = "^1.0"
serde_json = "^1.0"
serde = "^1.0"
